name: seismicloud
channels:
  - conda-forge
dependencies:
  - git
  - mpi4py
  - obspy
  - pandas
  - pip
  - python=3.9
  # - pytorch>=1.12.0=*cuda112*
  - tqdm
  - eqcorrscan
  - pip:
    - seisbench
    - git+https://github.com/wayneweiqiang/GaMMA.git
    - pyproj
