name: build-and-test

on:
  pull_request: 
    branches:
      - main
    paths-ignore:
      - '**/README.md'

env:
  IMAGE_NAME: seismicloud:test

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Test Image
        run: |
          docker images ls
          docker run --rm ${{ env.IMAGE_NAME }} conda list
